import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { StudentsProvider } from "@/context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StudentsProvider>
          <div className="flex min-h-screen bg-gray-50 dark:bg-gray-900 overflow-hidden gap-3">
            <Sidebar />
            <div className="flex flex-1 flex-col">
              <main>
                {children}
              </main>
            </div>
          </div>
        </StudentsProvider>
      </body>
    </html>
  );
}
